Testng homework
viktoria-anatsko/AutoTesting_Project pull request #1
Opened 2023-06-24 13:32 UTC by viktoria-anatsko

Add HomeWork TestNG

2023-06-26 14:39 UTC, wildpioneer requested changes

2023-06-26 14:39 UTC, wildpioneer commented on src/test/java/HomeWorkTest.java
> +    @Test(dataProvider = "Data for Division test", dataProviderClass = StaticProvider.class)
Отсутствую тесты на:
1)  @Parameters
2) retryAnalyzer

2023-07-03 14:12 UTC, viktoria-anatsko commented on src/test/java/HomeWorkTest.java
> +    @Test(dataProvider = "Data for Division test", dataProviderClass = StaticProvider.class)
Added methods paramTest and retryTest

2023-07-03 17:41 UTC, viktoria-anatsko commented
Александр, в файл HomeWorkTest.java добавила методы paramTest  и retryTest. У себя сделала commit and push, но не вижу изменений в удаленном репозитории, пока не разобралась, почему.

2023-07-03 19:05 UTC, viktoria-anatsko commented
Поправила. Теперь изменения видны.

2023-07-03 19:45 UTC, wildpioneer commented
Проверено

2023-07-03 19:45 UTC, closed without merging