Added Selenide homework
viktoria-anatsko/AutoTesting_Project pull request #12
Opened 2023-08-17 12:10 UTC by viktoria-anatsko

Added changes using Selenide.

2023-08-28 09:32 UTC, wildpioneer requested changes

2023-08-28 09:32 UTC, wildpioneer commented on src/test/java/tests/E2EShoppingTest.java
> +        shoppingStep.cartCheckout().isPageOpened();
Проверка одна - в конце теста

2023-09-03 10:20 UTC, viktoria-anatsko commented on src/test/java/tests/E2EShoppingTest.java
> +        shoppingStep.cartCheckout().isPageOpened();
Исправлено. Оставила одну проверку в конце.

2023-09-04 12:39 UTC, wildpioneer commented
Проверено

2023-09-04 12:39 UTC, closed without merging