Added BDD homework
viktoria-anatsko/AutoTesting_Project pull request #13
Opened 2023-08-25 09:54 UTC by viktoria-anatsko

Added Cucumber EndToEnd Test

2023-08-28 09:35 UTC, wildpioneer requested changes

2023-08-28 09:35 UTC, wildpioneer commented on src/test/java/RunCucumberTest.java
> +        glue = "stepDefs",
Используя такие значение в glue и tags - у меня не выполняется ни одного теста

2023-09-03 11:22 UTC, viktoria-anatsko commented on src/test/java/RunCucumberTest.java
> +        glue = "stepDefs",
Изменила.

2023-09-04 12:40 UTC, wildpioneer commented
Проверено

2023-09-04 12:40 UTC, closed without merging