Added SmokeTestHomework
viktoria-anatsko/AutoTesting_Project pull request #2
Opened 2023-07-05 14:57 UTC by viktoria-anatsko

2023-07-05 14:58 UTC, viktoria-anatsko commented
Homework Selenium WebDriver

2023-07-05 15:01 UTC, viktoria-anatsko commented
Не получилось в задании со звездочкой сделать проверку, не смогла определить правильный локатор.

2023-07-08 19:40 UTC, wildpioneer requested changes

2023-07-08 19:40 UTC, wildpioneer commented on pom.xml
> +        <dependency>
Эти зависимости лишние

2023-07-08 19:40 UTC, wildpioneer commented on src/test/java/SmokeTestHomework.java
> +    @Test
Между методами должна быть пустая строка

2023-07-11 08:33 UTC, viktoria-anatsko commented
Внесены рекомендуемые изменения.

2023-07-17 08:31 UTC, wildpioneer commented
Проверено

2023-07-17 08:31 UTC, closed without merging