Added Page Object homework
viktoria-anatsko/AutoTesting_Project pull request #4
Opened 2023-07-22 13:21 UTC by viktoria-anatsko

Page Object homework

2023-07-23 11:33 UTC, wildpioneer requested changes

2023-07-23 11:33 UTC, wildpioneer commented on src/test/java/baseEntities/BaseStep_.java
> +public class BaseStep_ {
Название класса не может содержать спецсимволы - удалить

2023-07-23 11:33 UTC, wildpioneer commented on src/test/java/pages/AuthorizationPage.java
> +    private final By errorTextLocator = By.className("error-message-container error");
Это неверный локатор - который не дает запустить нормально тесты

2023-07-23 11:33 UTC, wildpioneer commented on src/test/java/baseEntities/BaseTest_.java
> +public class BaseTest_ {
Название класса не может содержать спецсимволы - удалить

2023-07-23 11:33 UTC, wildpioneer commented on src/test/java/pages/InventoryPage.java
> +    private final By headerTitleLabelLocator = By.xpath("//*[@class='title']");
Это css или classname - зачем тут xPath?

2023-07-23 11:33 UTC, wildpioneer commented on src/test/java/pages/ShoppingCartContainerPage.java
> +    private final By shoppingCartBadgeLocator = By.xpath("//*[@class='shopping_cart_badge']");
Это css или classname - зачем тут xPath?

2023-07-23 11:33 UTC, wildpioneer commented on src/test/java/tests/ShoppingTest.java
> +    public void successShoppingTest() {
Отсутствует e2e тест

2023-07-23 15:49 UTC, viktoria-anatsko commented
Замечания учтены. Работу исправила.

2023-07-31 13:39 UTC, wildpioneer commented
Проверено

2023-07-31 13:39 UTC, closed without merging