Added Advanced Actions homework
viktoria-anatsko/AutoTesting_Project pull request #5
Opened 2023-07-23 14:03 UTC by viktoria-anatsko

Advanced Actions homework

2023-07-31 13:48 UTC, wildpioneer requested changes

2023-07-31 13:48 UTC, wildpioneer commented on src/test/java/tests/AlertHomeworkTest.java
> +    public void alertTest() {
А где Download test?

2023-08-01 12:35 UTC, viktoria-anatsko commented on src/test/java/tests/AlertHomeworkTest.java
> +    public void alertTest() {
Не сделала. Была ограничена во времени. Останется на самостоятельную работу )

2023-08-07 13:16 UTC, wildpioneer commented
Проверено

2023-08-07 13:16 UTC, closed without merging